/*
 * ServiceDesk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"
	"time"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "servicedesk/go"
)

func main() {
	port, ok := os.LookupEnv("PORT")
	if !ok {
		log.Fatal("PORT env is not set")
	}

	// костыль, чтобы до запуска сервиса успела подняться БД в контейнере с Postgres
	// по хорошему нужно переделать, чтобы функция в repository пыталась подключиться к БД
	// через определённые интервалы времени, и запустить её в отдельной горутине
	time.Sleep(15 * time.Second)
	sw.DBinit()
	router := sw.NewRouter()

	log.Printf("Server started on port %s", port)
	log.Fatal(http.ListenAndServe(port, router))
}
